Flatter TTL data without levelDB
mit-dci/utreexo pull request #279
Opened 2021-06-26 18:54 UTC by adiabat

This PR removes levelDB usage for the bridge node when dealing with TTL data, and instead stores the TTL data in 2 flat files, txidFile and txidOffsetFile.  

It seems to work now with stop & restart, and with a testnet3 sync it works pretty quickly, and results in 440MB of extra data, which seems very reasonable.  There are ways to decrease this further (txidOffsetFile is mostly zeros, and compresses from 14MB to 4MB.  txidFile doesn't compress, but there's still a lot of structure there.)
Anyway 440MB seems like no big deal so probably not worth working on reducing that.

I've commented out the memTTL options in this PR, as there's a bit of work to get the map-based TTL working without depending on levelDB.  Depending on the speed, it might not be worth it to keep in the map-based code as the flat file seems pretty fast, at least on the SSD I'm using.

Note that levelDB is still in the bridge node code to read the bitcoin blocks metadata.  It might be fun to eliminate levelDB entirely, but it's really only used in the first few seconds to figure out how to read the bitcoin rev files.

2021-06-27 07:02 UTC, kcalvinalvin commented
Regtest ci passes for me on a local build (after fixing some minor things) but am also getting this error consistently on testnet3 data when testing the binaries manually.

`Deserialize error from connection 127.0.0.1:8338 ud deser h 68088 nttl 23 targets 194 UtxoData[0] err bh 2400000001000213de00000000389758f0001976a9143bb508bf21c15119c134 op 0000000000000000000000000000000000000000ac88affafe952255d81c4525:0 pksize 33706 byte too long`

Can you confirm this?

2021-08-30 13:58 UTC, adiabat commented
OK this now works for regtest and testnet3 on my end, would be great if others can try it out.  I'll merge it if there are no other problems found.

2021-09-01 07:38 UTC, kcalvinalvin requested changes

2021-09-01 07:38 UTC, kcalvinalvin commented on bridgenode/config.go
> +<<<<<<< HEAD
Should remove the git merge conflicts here

2021-09-01 07:38 UTC, kcalvinalvin commented on bridgenode/config.go
> +	memTTL = argCmd.Bool("memttl", false,
If we're taking out the option for caching in ram, this flag should also be gone.

2021-09-01 07:38 UTC, kcalvinalvin commented on bridgenode/config.go
> +	// keep ttls in memory
If we're taking out the option for caching in ram, this field should be gone in the config

2021-09-01 07:38 UTC, kcalvinalvin commented on bridgenode/config.go
> +	cfg.memTTL = *memTTL
Refer to comments before. This should be gone if we're getting rid of caching

2021-09-01 07:38 UTC, kcalvinalvin commented on bridgenode/flatfileworker.go
> +			// case undo := <-undoChan:
I'm assuming commenting this code out is temporary?

2021-09-01 07:38 UTC, kcalvinalvin commented on bridgenode/flatfileworker.go
> +		// fmt.Printf("setting h=1\n")
Should delete this comment

2021-09-01 07:38 UTC, kcalvinalvin commented on bridgenode/flatfileworker.go
> +	// fmt.Printf("udata height %d flat file height %d\n",
Should delete these comments

2021-09-01 07:38 UTC, kcalvinalvin commented on bridgenode/flatfileworker.go
> +		// fmt.Printf("dest %d at loc %d = (heightOffset[%d] = %d) + 16 + (idx %d *4) \n",
Should delete these comments

2021-09-01 07:38 UTC, kcalvinalvin commented on bridgenode/flatfileworker.go
> +		// fmt.Printf("  writeTTLs overwrite byte %d with %x "+
Should delete these comments

2021-09-01 07:39 UTC, kcalvinalvin commented
Ok so the review doesn't really matter as much as commit `f051a5381c22be7a5d66947923fff6be6b51b3f7` doesn't restart for me.

Log:
```
Finished block 48000 of max 1923423                  
^CUser exit signal received. Exiting...
finished reading blocks, last height 48001                 
Done writing. Height 48001 Forest: can't print 50285 leaves. roots:
        0 8a701e97b83879ad08620df1
        1 13247ed533861d880ba53580             
        2 558cf1268abd9f3d5a68b37f
        3 3d5eb15c278c5e8184bf838d    
        4 6752c460effe8486bfa691f6
        5 12a9c1b34c6ab06196e4c3df             
        6 f912e22de9a8d0ccc1f0bb16
        7 5a405d0ce47f9a89aad01772                                                                                      
[N] calvin@bitcoin ~/b/g/u/g/s/g/m/u/c/utreexoserver ((f051a538…))> ./run.sh
Has access to forest, resuming
restore height 48001                                                                                                    
Starting forest: can't print 50285 leaves. roots:                                                                       
        0 8a701e97b83879ad08620df1
        1 13247ed533861d880ba53580             
        2 558cf1268abd9f3d5a68b37f
        3 3d5eb15c278c5e8184bf838d                                                                                      
        4 6752c460effe8486bfa691f6                                                                                      
        5 12a9c1b34c6ab06196e4c3df                                                                                      
        6 f912e22de9a8d0ccc1f0bb16
        7 5a405d0ce47f9a89aad01772                                                                                      
                                                                                                                        
Building Proofs and ttls...                                                                                             
panic: writeTTLs Wanted to overwrite byte 10263779 with 00000003 but 2d3038c3 was already there. desth 48022 createh 48019 idxinblk 20
                                                            
goroutine 15 [running]:          
github.com/mit-dci/utreexo/bridgenode.FlatFileWriter(0xc0004fc240, 0xc0004fc1e0, 0xc00001e378, 0x13, 0xc00001a420, 0x22, 0xc000020800, 0x31, 0xc00001e390, 0x12, ...)
        /home/calvin/bitcoin-projects/go/utreexo/go/src/github.com/mit-dci/utreexo/bridgenode/flatfileworker.go:123 +0x53e
created by github.com/mit-dci/utreexo/bridgenode.BuildProofs     
        /home/calvin/bitcoin-projects/go/utreexo/go/src/github.com/mit-dci/utreexo/bridgenode/genproofs.go:117 +0x3a8
[I] calvin@bitcoin ~/b/g/u/g/s/g/m/u/c/utreexoserver ((f051a538…)) [2]> git log
```

2021-11-08 14:51 UTC, adiabat commented
Tested with all of testnet data, looks fine.  There might be other bugs but will merge this now.

2021-11-08 14:52 UTC, merged